---
name: fashion_store_app_ui
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  get: ^4.1.4
  timeago: ^3.1.0
  flutter_svg: ^0.22.0
  riverpod: ^0.14.0+3
  page_transition: ^2.0.2
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
